//IMPORT MODULE

import Head from "next/head";

//IMPORT SRC
import Header from '../components/Landing/Header/Header';
import Footer from '../components/Landing/Footer/Footer';
import { Section1, Section2, Section3, Section4 } from '../components/Landing/Main/index'

import { LanguagesPNG } from '../components/utils/Paths'; 

{ /* <FirebaseDatabaseNode
  path="user_bookmarks/"
  limitToFirst={this.state.limit}
  // orderByKey
  orderByValue={"created_on"}
>
  {d => {
    return (
      <React.Fragment>
        <pre>Path {d.path}</pre>
        <pre style={{ height: 300, overflow: "auto" }}>
          Value {s(d.value)}
        </pre>
        <button
          onClick={() => {
            this.setState(state => ({ limit: state.limit + 2 }));
          }}
        >
          Load more
        </button>
      </React.Fragment>
    );
  }}
</FirebaseDatabaseNode> */}





export default function Home() {
  return (
    <>
      <Head>
        <title>Javier Lopez Galache</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="main_section" className="font-sans bg-yellow-100">
        <div className="mt-0">
          <Header />
            <Section1 />
            <Section2 />
            <Section3 />
            <Section4 />
        <Footer />
      </div>
      </div>
    </>
  );
}


/* 
export async function getStaticProps() {
  console.log(LanguagesPNG);
  const filenames = FilepathFinder(LanguagesPNG);
  console.log(filenames);
  return {
    props: {
      filenames,
    },
  };
}
 */